config/routes.rb
Rails.application.routes.draw do
  root                           'main#index'
  get 'help'                  => 'main#help'
  get 'signup'                => 'users#new'
  get 'login'                 => 'sessions#new'
  post 'login'                => 'sessions#create'
  delete 'logout'             => 'sessions#destroy'
  get 'competitions'          => 'competitions#index'
  get '/competitions/(:id)'   => 'competitions#select_photos'
  get '/info/(:id)'           => 'competitions#show_info'
  get '/results/(:id)'        => 'competitions#results'

  resources :users do
    member do
      #get :following, :followers #users/1/following users/1/followers
      get 'following'
      get 'followers'
    end
  end

  resources :albums #обеспечивает автоматический вызов всех методов REST
  resources :photos
  resources :values
  resources :comments
  resources :relationships, only: [:create, :destroy]

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  def index
    @albums = Album.where("competition = 'true'")
  end

  def select_photos
    #@photos = Album.find(params[:id]).photos.pluck(:file)
    @photos = Album.find(params[:id]).photos
    respond_to do |format|
      format.json { render json: @photos }
    end
  end

  def show_info
    @photo = Photo.find(params[:id])
    respond_to do |format|
      format.json { render json: @photo }
    end
  end

  def results
    @photos = Album.find(params[:id]).photos
  end



end

app/helpers/competitions_helper.rb
module CompetitionsHelper
end

app/views/competitions/_rate.html.slim
.value-form
  'Твой голос важен для участников.
  'Поставь оценку, если фотография тебе нравится!

  = form_for :value, url: values_path, html: {id: 'rating-form'} do |f|
    .rating.half-down
      = f.label 1, class: 'rate-label'
      = f.radio_button :value, '1'

      = f.label 2, class: 'rate-label'
      = f.radio_button :value, '2'

      = f.label 3, class: 'rate-label'
      = f.radio_button :value, '3'

      = f.label 4, class: 'rate-label'
      = f.radio_button :value, '4'

      = f.label 5, class: 'rate-label'
      = f.radio_button :value, '5'

      = f.hidden_field :user_id, value: current_user.id
      .photo-id
      /из js = f.hidden_field :photo_id
      = f.submit 'Оценить', class: 'btn btn-primary'
  .half-down
    .album-id
      /из js = link_to 'Посмотреть результаты голосования', '/results', class: "btn btn-xs btn-link"


app/views/competitions/index.html.slim
= provide(:title, t('shared.header.competitions'))

.row
  /select & carousel
  h1 Выбери конкурс
  #select_competitions
    = select_tag ':albums', options_from_collection_for_select(@albums, :id, :album_name),
            class: 'form-control'
.row.down

  #myCarousel.carousel.col-md-8.slide[ data-interval="false"]
    /data-ride="carousel" авто прокрутка
    .carousel-inner[role="listbox"]

    a.left.carousel-control[href="#myCarousel" role="button" data-slide="prev"]
      i.fa.fa-arrow-circle-left.icon.icon-left aria-hidden="true"
      span.sr-only Previous
    a.right.carousel-control[href="#myCarousel" role="button" data-slide="next"]
      i.fa.fa-arrow-circle-right.icon.icon-right aria-hidden="true"
      span.sr-only Next

  /values
  #rates.col-md-4
    = render 'rate'

app/views/competitions/results.html.slim
/должно быть отображение общих результатов голосования в табличной форме по всем картинкам

h1 Результаты голосования

table.table.table-striped
  thead
    tr
      th Фото
      th Средняя оценка
      th Проголосовало пользователей
  tbody
    - @photos.each do |photo|
      tr
        td
          = image_tag photo.file_url, height: '100'
        td = photo.values.average(:value)
        td = photo.values.count

br

= link_to 'Голосовать еще', competitions_path