config/routes.rb
Rails.application.routes.draw do
  root                           'main#index'
  get 'help'                  => 'main#help'
  get 'signup'                => 'users#new'
  get 'login'                 => 'sessions#new'
  post 'login'                => 'sessions#create'
  delete 'logout'             => 'sessions#destroy'
  get 'competitions'          => 'competitions#index'
  get '/competitions/(:id)'   => 'competitions#select_photos'
  get '/info/(:id)'           => 'competitions#show_info'
  get '/results/(:id)'        => 'competitions#results'

  resources :users do
    member do
      #get :following, :followers #users/1/following users/1/followers
      get 'following'
      get 'followers'
    end
  end

  resources :albums #обеспечивает автоматический вызов всех методов REST
  resources :photos
  resources :values
  resources :comments
  resources :relationships, only: [:create, :destroy]

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_album_form.html.slim
= form_for(@album, html: { multipart: true }) do |f|
  = render 'shared/error_message', object: f.object

  - if current_user.admin?
    = f.check_box :competition, value: 'true'
    |  конкурсный альбом
  - else
    = hidden_field_tag :competition, 'false'

  = f.label :album_name, 'Название альбома'
  = f.text_field :album_name, class: 'form-control'
  .half-down
  = f.label :album_description, 'Описание альбома'
  = f.text_area :album_description, class: 'form-control', placeholder: 'Опишите о чем ваш альбом...'
  .photo-form
  = f.fields_for :photos, Photo.new do |photo_fields|

    = photo_fields.file_field :file, accept: 'image/jpeg, image/gif, image/png'

  .half-down
  = f.submit t('shared.album.create'), class: 'btn btn-primary'


app/views/shared/_competition_form.html.slim
= form_for(Album.new, html: { multipart: true }) do |f|
  = render 'shared/error_message', object: f.object

  = hidden_field_tag :competition, 'true'

  = f.label :album_name, 'Название альбома'
  = f.text_field :album_name, class: 'form-control'
  .half-down
  = f.label :album_description, 'Описание альбома'
  = f.text_area :album_description, class: 'form-control',
          placeholder: 'Опишите условия конкурса и срои его проведения...'
  .photo-form
  = f.fields_for :photos, Photo.new do |photo_fields|

    = photo_fields.file_field :file, accept: 'image/jpeg, image/gif, image/png'

  .half-down
  = f.submit t('shared.album.create'), class: 'btn btn-primary'

app/views/shared/_error_message.html.slim
- if object.errors.any?
  #error_explanation
    .alert.alert-danger
      |  Форма содержит ошибки:
      / =pluralize(@user.errors.count, "ошибка")
    ul
      - object.errors.full_messages.each do |msg|
        li
          = msg

app/views/shared/_feed.html.slim
- if @feed_items.any?
  ol.albums
    = render @feed_items
  = will_paginate @feed_items

app/views/shared/_footer.html.slim
footer.footer
  .container
    .row.text-center
      p.text-muted
        | My first Ruby-project

app/views/shared/_header.html.slim

.navbar.navbar-inverse.navbar-fixed-top[role="navigation"]
  .container
    .navbar-collapse.collapse
      ul.nav.navbar-nav
        li.active =link_to 'Ruby-project', root_path
        li = link_to t('.help'), help_path

        - if logged_in?
          li
            = link_to t('.users'), users_path
          li
            = link_to t('.albums'), albums_path
          li
            = link_to t('.competitions'), competitions_path

          li.dropdown
            a.dropdown-toggle[href="#" data-toggle="dropdown"]
              = t('.account')
              b.caret
            ul.dropdown-menu
              li
                = link_to t('.profile'), current_user
              li
                = link_to t('.settings'), edit_user_path(current_user)
              li.divider
              li
                = link_to t('.log_out'), logout_path, method: 'delete'
        - else
          li
            = link_to t('.log_in'), login_path

        li = link_to 'RU', locale: :ru
        li = link_to 'EN', locale: :en
        b
          = I18n.locale



app/views/shared/_photo_form.html.slim
= form_for(@album, html: { multipart: true }) do |f|
  = render 'shared/error_message', object: f.object

  = f.fields_for :photos, Photo.new do |photo_fields|

    = photo_fields.file_field :file, accept: 'image/jpeg, image/gif, image/png'
  .half-down
  = f.submit 'Добавить фото', class: 'btn btn-primary'

app/views/shared/_stats.html.slim
- @user ||= current_user
.stats
  a href="#{following_user_path(@user)}"
    strong#following.stat
      = @user.following.count
    |  following
  br
  a href="#{followers_user_path(@user)}"
    strong#followers.stat
      = @user.followers.count
    |  followers
    ' followers

app/views/shared/_user_info.html.slim
= link_to gravatar_for(current_user, size: 60), current_user
h1
  = current_user.name
span
  = link_to 'посмотреть мой профиль', current_user
br
/span
  = pluralize(current_user.albums.count, 'album')