config/routes.rb
Rails.application.routes.draw do
  root                           'main#index'
  get 'help'                  => 'main#help'
  get 'signup'                => 'users#new'
  get 'login'                 => 'sessions#new'
  post 'login'                => 'sessions#create'
  delete 'logout'             => 'sessions#destroy'
  get 'competitions'          => 'competitions#index'
  get '/competitions/(:id)'   => 'competitions#select_photos'
  get '/info/(:id)'           => 'competitions#show_info'
  get '/results/(:id)'        => 'competitions#results'

  resources :users do
    member do
      #get :following, :followers #users/1/following users/1/followers
      get 'following'
      get 'followers'
    end
  end

  resources :albums #обеспечивает автоматический вызов всех методов REST
  resources :photos
  resources :values
  resources :comments
  resources :relationships, only: [:create, :destroy]

# For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/album.rb
class Album < ApplicationRecord
  belongs_to :user
  has_many :photos, dependent: :destroy
  accepts_nested_attributes_for :photos, :allow_destroy => true #добавляет вложенные атрибуты
  default_scope -> { order(created_at: :desc)} #задает порядок показа альбомов
  validates :user_id, presence: true #проверка user_id в album
  validates :album_name, presence: true, length: {maximum: 100}
  validates :album_description, presence: true, length: {maximum: 200}

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user, only: [:destroy, :update]

  def index
    @albums = Album.paginate(page: params[:page])
  end

  def new
    @album = Album.new
    @album.photos.build_album
  end

  def create
    @album = current_user.albums.build(album_params) #создает новое взаимоотношение, запрос post
    if @album.save
      redirect_to root_url, notice: "Альбом сохранен!"
    else
      @feed_items = []
      render 'main/index'
    end
  end

  def edit
  end

  def show
    @album = Album.find(params[:id])
    render 'albums/show'
  end

  def update
    @album = Album.find_by_id(params[:id])
    if @album.update_attributes(album_params)
      #обработать успешное изменение
      redirect_to root_url, notice: 'Альбом обновлен'
    else
      render 'edit'
    end
  end

  def destroy
    @album.destroy
    redirect_to request.referrer || root_url, notice: 'Альбом удален'
    #request.referrer - переадресует на предыдущий url
  end

  #определяем строгие параметы, что можно редактировать
  private
    def album_params
      params.require(:album).permit(:competition, :album_name, :album_description,
                                    photos_attributes: [:id, :album_id, :file, :ave_value, :_destroy])
    end

    def correct_user
      @album = current_user.albums.find_by(id: params[:id])
      redirect_to root_url if @album.nil?
    end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/views/albums/_album.html.slim
li.down id="album-#{album.id}"
  = link_to gravatar_for(album.user, size: 50), album.user
  br
    span.user
      = link_to album.user.name, album.user
  br
    span.album-name
      |Название альбома:
      br
      = link_to album.album_name, album
  br
    span.album-description
      |Описание альбома:
      br
      = album.album_description
  br
    .photo
      = image_tag album.photos.first.file_url if album.photos !=[]


    span.timestamp
      /| Альбом создан
      /= time_ago_in_words(album.created_at)
      /| назад.
      br
      = album.photos.count
      |  фото в альбоме
      br
    = link_to 'Посмотреть альбом', album_path(album.id),  class: 'btn btn-link btn-xs'
    - if current_user?(album.user)

        = link_to 'Редактировать название и описание альбома',
                edit_album_path(album.id), class: 'btn btn-link btn-xs'

        = link_to 'Удалить альбом', album, method: :delete, class: 'btn btn-link btn-xs',
                                  data: {confirm: 'Удалить альбом?'}


app/views/albums/_comment_form.html.slim
/надо получить id фото
/ form_for :comment, url: comments_path, remote: true, html: {id: 'comment-form'}do |f|
  = f.hidden_field :user_id, value: current_user.id
  = f.hidden_field :photo_id, value: photo.id
  = f.label :content, 'Твой коммент'
  = f.text_area :content, class: 'form-control',
          placeholder: 'Нравится? - Скажи!'
  .half-down
    = f.submit 'Отправить', class: 'btn btn-s btn-primary'

app/views/albums/edit.html.slim
= provide(:title, t('albums.edit.edit_album'))

.row
  h1 = t('albums.edit.edit_album')

.row
  .col-md-6.col-md-offset-3
    = form_for Album.find(params[:id]) do |f|
      = render 'shared/error_message', object: f.object

      = f.label :album_name, 'Название альбома'
      = f.text_field :album_name, class: 'form-control'

      = f.label :album_description, 'Описание альбома'
      = f.text_area :album_description, class: 'form-control', placeholder: 'Опишите о чем ваш альбом...'

      = f.submit 'Изменить альбом', class: 'btn btn-primary'

app/views/albums/index.html.slim
= provide(:title, t('shared.header.albums'))

.row
  h1 = t('shared.header.albums')

  = will_paginate

  ul.albums
    = render @albums
  /@@albums - список объектов Albums, Rails автоматически перебирает ее
      и отображает каждый элемент коллекции с помощью шаблона _album
  = will_paginate

app/views/albums/show.html.slim
= provide(:title, t('.album'))

.row

  - if @album.photos.any?


    h3 = @album.album_name
    .down
      - if current_user?(@album.user)
        = render 'shared/photo_form'
    .all-photo.down
      - @album.photos.each do |photo|
        .row.line
          .photo.col-md-8
            = image_tag photo.file_url
            - if current_user?(@album.user)
              br
              = link_to 'Удалить фотографию', album_path(@album.id,
                      album: {photos_attributes: {id: photo.id, _destroy: true}}),
                      remote: true, confirm: 'Really delete?', method: :put
          .col-md-4
            /Comments
            /= render 'albums/comment_form'
            = form_for :comment, url: comments_path, remote: true, html: {id: 'comment-form'}do |f|
              = f.hidden_field :user_id, value: current_user.id
              = f.hidden_field :photo_id, value: photo.id
              = f.label :content, 'Твой коммент'
              = f.text_area :content, class: 'form-control',
                      placeholder: 'Нравится? - Скажи!'
              .half-down
                = f.submit 'Отправить', class: 'btn btn-s btn-primary'
              /= render 'comments/index'

  - else
    .down
      - if current_user?(@album.user)
        |В альбоме еще нет фотографий. Хотите добавить?
        .half-down
        = render 'shared/photo_form'
      - else
        |В альбоме нет фотографий

          /= link_to "Delete", question_path(question.id, пример
              /question: { answers_attributes: { id: question.answers.id, "_destroy" => true }}),
              /remote: true, confirm: "Really delete?", method: :put